[window]
opacity = 0.8
blur = true
startup_mode = "Maximized"
padding.x = 10
padding.y = 10
decorations = "None"
decorations_theme_variant = "Dark"

[font]
size = 8.0

[cursor]
style.shape = "Underline"
style.blinking = "Always"
vi_mode_style.shape = "Underline"
vi_mode_style.blinking = "Always"
blink_interval = 300
blink_timeout = 0
unfocused_hollow = false
thickness = 0.07

[mouse]
hide_when_typing = true

# tokyo-night colors
[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

[colors.normal]
black = '#32344a'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#ad8ee6'
cyan = '#449dab'
white = '#787c99'

[colors.bright]
black = '#444b6a'
red = '#ff7a93'
green = '#b9f27c'
yellow = '#ff9e64'
blue = '#7da6ff'
magenta = '#bb9af7'
cyan = '#0db9d7'
white = '#acb0d0'
